apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ttoykm3pu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ttoykm3pu-go 
  name: ttoykm3pu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ttoykm3pu-go 
